name: drink_eazy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  pinput: ^5.0.0

  # API / Backend
  provider: ^6.1.5+1
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^6.0.0
  connectivity_plus: ^7.0.0

  # Camera - QR
  mobile_scanner: ^7.1.3
  image_picker: ^1.2.0

  # Toasts
  motion_toast: ^2.14.0
  fluttertoast: ^9.0.0

  # Animations
  animated_splash_screen: ^1.3.0
<<<<<<< HEAD
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.5.3

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
=======
  confetti: ^0.7.0

  # Tools
  intl: ^0.18.1
  path_provider: ^2.0.15
  pdf: ^3.11.0
  printing: ^5.10.0

  # FIXED ðŸ‘‡
  share_plus: ^12.0.1
  url_launcher: ^6.1.10
>>>>>>> 014d82e05e8ef63d4454beaebaa80d22af877097

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/DrinkEasyLogo.png
    - assets/images/bgimage2.jpg
    - .env

  fonts:
    - family: Agbalumo
      fonts:
        - asset: assets/fonts/Agbalumo-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/DrinkEasyLogoIcone.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/DrinkEasyLogoIcone.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/DrinkEasyLogo.png

  android_12:
    image: assets/images/DrinkEasyLogo.png
    color: "#ffffff"

  android: true
  ios: true
  web: false
